name: plm_app_final
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^2.0.0


  cupertino_icons: ^1.0.2
  division: ^0.9.0
  url_launcher: ^6.0.17
  introduction_screen: ^2.1.0
  flutter_swiper: ^1.1.6
  carousel_slider: ^4.0.0
  flutter_login: ^3.1.0
  linkwell: ^2.0.6
  maps_launcher: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/PLM.jpg
    - assets/On1.jpg
    - assets/On2.jpg
    - assets/On3.jpg
    - assets/PLMSeal.png
    - assets/googlemapicon.png
    - assets/vicinitymap.png
    - assets/arrowhead.png
    - assets/arrowheadright.png
    - assets/plmimage.png
    - assets/visitplmwebsite.png
    - assets/Telephone.jpg
    - assets/arrowleft.png
    - assets/arrowright.png
    - assets/no1_highlighted.png
    - assets/no2_highlighted.png
    - assets/no3_highlighted.png
    - assets/no4_highlighted.png
    - assets/no5_highlighted.png
    - assets/no6_highlighted.png
    - assets/no7_highlighted.png
    - assets/no1.png
    - assets/no2.png
    - assets/no3.png
    - assets/no4.png
    - assets/no5.png
    - assets/no6.png
    - assets/no7.png
    - assets/admissions.png
    - assets/images/clock_icon.png
    - assets/account_info.png
    - assets/calendar.png
    - assets/change_pass.png
    - assets/dark_mode.png
    - assets/language.png
    - assets/messages.png
    - assets/notif.png
    - assets/photos.png
    - assets/privacy_secu.png
    - assets/profile_pic.png
    - assets/transactions.png
    - assets/plm_pic.png
    - assets/profilebg.png
    - assets/profilepic.png
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Light.ttf
